### ISSUE TITLE
Throws "Directory not exists" error 

### ISSUE THREAD

**Issue by Super-Kenil** [serwus79/heic2jpg#1]
**OS**: Windows

**Bug**: Throws "Directory not exists" error when there's space in folder/directory name

**Expected Behavior** : Path to folder should be found and images should be converted normally even when there are spaces '' " in the folder name

**Comment by serwus79** [comment]
Hi,
Thanks for checking out this code.

You can use folders with spaces by sorrounding path with quotes (cmd) or apostrophes (powershell):

`heic-dir-convert --directory "E:\Photos test"`

`heic-dir-convert --directory 'E:\Photos test\'`

**Comment by Super-Kenil** [comment]
Thank you for the solution. Really appreciate it
